;;; post-early-init.el --- After early-init -*- lexical-binding: t; -*-

;; Loaded after minimal-emacs.d's early-init.el, before init.el.
;; Generated by tangling Config.org -- do not hand-edit; edit Config.org instead.
;; (Stub: currently unused; Config.org does not yet tangle here.)

;;; Code:

(provide 'post-early-init)
;;; post-early-init.el ends here
