;;; post-init.el --- E6's config (tangled from Config.org) -*- lexical-binding: t; -*-
;;; Commentary:
;;  DO NOT EDIT.  This file is generated by tangling Config.org.
;;  Edit Config.org instead; saving it re-tangles this file.
;;; Code:

(defun e6/auto-tangle-config ()
  "Tangle the Emacs `Config.org' when it is saved."
  (when (and buffer-file-name
             (string-equal (file-name-nondirectory buffer-file-name)
                           "Config.org"))
    (let ((org-confirm-babel-evaluate nil)
          (message-log-max nil)
          (inhibit-message t))
      (require 'org)
      (org-babel-tangle))))

(add-hook 'after-save-hook #'e6/auto-tangle-config)

(defconst e6/windows-p (eq system-type 'windows-nt)
  "Non-nil when running on Windows.")
(defconst e6/linux-p (eq system-type 'gnu/linux)
  "Non-nil when running on Linux.")
(defconst e6/mac-p (eq system-type 'darwin)
  "Non-nil when running on macOS.")

;; Remember recently opened files.
(add-hook 'after-init-hook #'recentf-mode)
;; Persist minibuffer history between sessions.
(add-hook 'after-init-hook #'savehist-mode)
;; Reopen files at the last cursor position.
(add-hook 'after-init-hook #'save-place-mode)
;; Keep buffers in sync with files changed on disk (e.g. after a git pull).
(add-hook 'after-init-hook #'global-auto-revert-mode)

;; Show matching parens.
(add-hook 'after-init-hook #'show-paren-mode)
;; Soft-wrap long lines in text/prose buffers (writing-first).
(add-hook 'text-mode-hook #'visual-line-mode)
;; Type over the active region.
(add-hook 'after-init-hook #'delete-selection-mode)

(add-hook 'after-init-hook #'which-key-mode)

(when (display-graphic-p)
  (load-theme 'modus-vivendi :no-confirm))

(when (display-graphic-p)
  ;; Monospace: FiraCode Nerd Font.
  (when (find-font (font-spec :name "FiraCode Nerd Font"))
    (set-face-attribute 'default nil :family "FiraCode Nerd Font" :height 120)
    (set-face-attribute 'fixed-pitch nil :family "FiraCode Nerd Font"))
  ;; Variable/prose: Gentium Plus.
  (when (find-font (font-spec :name "Gentium Plus"))
    (set-face-attribute 'variable-pitch nil :family "Gentium Plus" :height 130)))

(provide 'post-init)
;;; post-init.el ends here
