;;; post-init.el --- E6's config (tangled from Config.org) -*- lexical-binding: t; -*-
;;; Commentary:
;;  DO NOT EDIT.  This file is generated by tangling Config.org.
;;  Edit Config.org instead; saving it re-tangles this file.
;;; Code:

(defun e6/auto-tangle-config ()
  "Tangle the Emacs `Config.org' when it is saved."
  (when (and buffer-file-name
             (string-equal (file-name-nondirectory buffer-file-name)
                           "Config.org"))
    (let ((org-confirm-babel-evaluate nil)
          (message-log-max nil)
          (inhibit-message t))
      (require 'org)
      (org-babel-tangle))))

(add-hook 'after-save-hook #'e6/auto-tangle-config)

(defconst e6/windows-p (eq system-type 'windows-nt)
  "Non-nil when running on Windows.")
(defconst e6/linux-p (eq system-type 'gnu/linux)
  "Non-nil when running on Linux.")
(defconst e6/mac-p (eq system-type 'darwin)
  "Non-nil when running on macOS.")

;; Remember recently opened files.
(add-hook 'after-init-hook #'recentf-mode)
;; Persist minibuffer history between sessions.
(add-hook 'after-init-hook #'savehist-mode)
;; Reopen files at the last cursor position.
(add-hook 'after-init-hook #'save-place-mode)
;; Keep buffers in sync with files changed on disk (e.g. after a git pull).
(add-hook 'after-init-hook #'global-auto-revert-mode)

;; Show matching parens.
(add-hook 'after-init-hook #'show-paren-mode)
;; Soft-wrap long lines in text/prose buffers (writing-first).
(add-hook 'text-mode-hook #'visual-line-mode)
;; Type over the active region.
(add-hook 'after-init-hook #'delete-selection-mode)

(add-hook 'after-init-hook #'which-key-mode)

(use-package fontaine
  :if (display-graphic-p)
  :config
  (setq fontaine-presets
        '((default
           :default-family "FiraCode Nerd Font"
           :default-height 120
           :fixed-pitch-family "FiraCode Nerd Font"
           :variable-pitch-family "Gentium Plus"
           :variable-pitch-height 1.15)))
  ;; Persist and restore the last-used preset across sessions.
  (fontaine-mode 1)
  (fontaine-set-preset (or (fontaine-restore-latest-preset) 'default)))

(use-package nano-theme
  :config
  (load-theme 'nano-dark :no-confirm))

(use-package nano-modeline
  :init
  (setq nano-modeline-position 'nano-modeline-footer)
  :hook
  ((prog-mode . nano-modeline-prog-mode)
   (text-mode . nano-modeline-text-mode)
   (org-mode  . nano-modeline-org-mode)))

(use-package spacious-padding
  :if (display-graphic-p)
  :config
  (spacious-padding-mode 1))

;; Prose gets the variable-pitch font; code/tables stay fixed-pitch.
(use-package mixed-pitch
  :hook ((org-mode  . mixed-pitch-mode)
         (text-mode . mixed-pitch-mode)))

;; Modern Org rendering.
(use-package org-modern
  :config
  (with-eval-after-load 'org
    (global-org-modern-mode)))

;; Reveal emphasis markers only around point.
(use-package org-appear
  :hook (org-mode . org-appear-mode))

(with-eval-after-load 'org
  (setq org-hide-emphasis-markers t
        org-pretty-entities t))

(use-package diminish
  :config
  (with-eval-after-load 'which-key  (diminish 'which-key-mode))
  (with-eval-after-load 'mixed-pitch (diminish 'mixed-pitch-mode))
  (with-eval-after-load 'org-appear (diminish 'org-appear-mode))
  (diminish 'visual-line-mode)
  (with-eval-after-load 'autorevert (diminish 'auto-revert-mode)))

(provide 'post-init)
;;; post-init.el ends here
