;;; post-init.el --- E6's config (tangled from Config.org) -*- lexical-binding: t; -*-
;;; Commentary:
;;  DO NOT EDIT.  This file is generated by tangling Config.org.
;;  Edit Config.org instead; saving it re-tangles this file.
;;; Code:

(defun e6/auto-tangle-config ()
  "Tangle the Emacs `Config.org' when it is saved."
  (when (and buffer-file-name
             (string-equal (file-name-nondirectory buffer-file-name)
                           "Config.org"))
    (let ((org-confirm-babel-evaluate nil)
          (message-log-max nil)
          (inhibit-message t))
      (require 'org)
      (org-babel-tangle))))

(add-hook 'after-save-hook #'e6/auto-tangle-config)

(defconst e6/windows-p (eq system-type 'windows-nt)
  "Non-nil when running on Windows.")
(defconst e6/linux-p (eq system-type 'gnu/linux)
  "Non-nil when running on Linux.")
(defconst e6/mac-p (eq system-type 'darwin)
  "Non-nil when running on macOS.")

;; Remember recently opened files.
(add-hook 'after-init-hook #'recentf-mode)
;; Persist minibuffer history between sessions.
(add-hook 'after-init-hook #'savehist-mode)
;; Reopen files at the last cursor position.
(add-hook 'after-init-hook #'save-place-mode)
;; Keep buffers in sync with files changed on disk (e.g. after a git pull).
(add-hook 'after-init-hook #'global-auto-revert-mode)

;; Show matching parens.
(add-hook 'after-init-hook #'show-paren-mode)
;; Soft-wrap long lines in text/prose buffers (writing-first).
(add-hook 'text-mode-hook #'visual-line-mode)
;; Type over the active region.
(add-hook 'after-init-hook #'delete-selection-mode)

(add-hook 'after-init-hook #'which-key-mode)

(use-package fontaine
  :if (display-graphic-p)
  :config
  ;; 12pt body (height 120 = 12.0pt). No serif: variable-pitch also uses the
  ;; sans/mono FiraCode so nothing turns serif. Change -variable-pitch-family to
  ;; a sans you like (e.g. "DejaVu Sans") if you want proportional prose later.
  (setq fontaine-presets
        '((default
           :default-family "FiraCode Nerd Font"
           :default-height 120
           :fixed-pitch-family "FiraCode Nerd Font"
           :variable-pitch-family "FiraCode Nerd Font"
           :variable-pitch-height 1.0)))
  (fontaine-mode 1)
  (fontaine-set-preset (or (fontaine-restore-latest-preset) 'default)))

(use-package nano-theme
  :config
  (load-theme 'nano-dark :no-confirm))

(use-package nano-modeline
  :init
  (setq nano-modeline-position 'nano-modeline-footer)
  :hook
  ((prog-mode . nano-modeline-prog-mode)
   (text-mode . nano-modeline-text-mode)
   (org-mode  . nano-modeline-org-mode)))

(use-package spacious-padding
  :if (display-graphic-p)
  :config
  (spacious-padding-mode 1))

;; Prose in the variable-pitch font (off by default; toggle with SPC t m).
;; Not auto-enabled: with a serif variable-pitch it hurt readability, and you
;; prefer a single readable face. Toggle it on per buffer if you want it.
(use-package mixed-pitch
  :commands (mixed-pitch-mode))

;; Modern Org rendering.
(use-package org-modern
  :config
  (with-eval-after-load 'org
    (global-org-modern-mode)))

;; Reveal emphasis markers only around point.
(use-package org-appear
  :hook (org-mode . org-appear-mode))

(with-eval-after-load 'org
  (setq org-hide-emphasis-markers t
        org-pretty-entities t))

(use-package diminish
  :config
  (with-eval-after-load 'which-key  (diminish 'which-key-mode))
  (with-eval-after-load 'mixed-pitch (diminish 'mixed-pitch-mode))
  (with-eval-after-load 'org-appear (diminish 'org-appear-mode))
  (diminish 'visual-line-mode)
  (with-eval-after-load 'autorevert (diminish 'auto-revert-mode)))

(use-package dirvish
  :init
  (dirvish-override-dired-mode)
  :custom
  (dirvish-quick-access-entries
   '(("h" "~/" "Home") ("o" "~/org/" "Org") ("d" "~/Downloads/" "Downloads")))
  :config
  (setq dirvish-attributes
        '(nerd-icons file-time file-size collapse subtree-state vc-state)
        dirvish-side-attributes '(nerd-icons collapse file-size))
  ;; Minibuffer file preview. Its module/name varies across dirvish versions
  ;; (differs between machines), so load and enable it defensively.
  (when (or (fboundp 'dirvish-peek-mode)
            (require 'dirvish-peek nil t))
    (dirvish-peek-mode))
  :bind (:map dirvish-mode-map
         ("a"   . dirvish-quick-access)
         ("TAB" . dirvish-subtree-toggle)
         ("h"   . dirvish-history-jump)
         ("s"   . dirvish-quicksort)
         ("f"   . dirvish-file-info-menu)))

;; Wrapper so the menu entry is always a valid command (dirvish-side lives in a
;; module that isn't always autoloaded, and versions differ between machines).
(defun e6/dirvish-side ()
  "Open the Dirvish sidebar, loading it if needed."
  (interactive)
  (or (require 'dirvish-side nil t) (require 'dirvish nil t))
  (if (fboundp 'dirvish-side)
      (call-interactively 'dirvish-side)
    (user-error "dirvish-side is unavailable in this dirvish version")))

(use-package project
  :ensure nil
  :config
  (setq project-vc-extra-root-markers '(".project" ".projectile")))

(require 'transient)
(transient-define-prefix e6/project-menu ()
  "Project (project.el)."
  [["Navigate"
    ("p" "Switch project" project-switch-project)
    ("f" "Find file"      project-find-file)
    ("b" "Switch buffer"  project-switch-to-buffer)
    ("d" "Dired"          project-dired)]
   ["Search / act"
    ("g" "Grep"           project-find-regexp)
    ("r" "Replace"        project-query-replace-regexp)
    ("c" "Compile"        project-compile)
    ("!" "Shell command"  project-shell-command)]])

(use-package olivetti
  ;; Text-type buffers only (Org, Markdown/QMD derive from text-mode); code
  ;; buffers keep their normal full-width indentation.
  :hook ((text-mode . olivetti-mode)
         (org-mode  . olivetti-mode))
  :custom
  (olivetti-body-width 90)
  (olivetti-minimum-body-width 60)
  (olivetti-style 'fancy)   ; fringes + margins → the darker flanks (see fringe face)
  :config
  (with-eval-after-load 'diminish (diminish 'olivetti-mode)))

(use-package org-sticky-header
  :hook (org-mode . org-sticky-header-mode)
  :custom
  (org-sticky-header-full-path 'full)
  (org-sticky-header-outline-path-separator " / "))

(defun e6/apply-nord-org-headings (&rest _)
  "Colour/size Org headings (Nord); keep code faces monospaced; darken fringe."
  (let ((specs '((org-document-title "#88C0D0" 1.5)
                 (org-level-1        "#88C0D0" 1.30)   ; frost cyan
                 (org-level-2        "#81A1C1" 1.20)   ; frost blue
                 (org-level-3        "#8FBCBB" 1.15)   ; frost teal
                 (org-level-4        "#5E81AC" 1.10)   ; deep blue
                 (org-level-5        "#B48EAD" 1.05)   ; aurora purple
                 (org-level-6        "#A3BE8C" 1.05)   ; aurora green
                 (org-level-7        "#EBCB8B" 1.00)   ; aurora yellow
                 (org-level-8        "#D08770" 1.00))))  ; aurora orange
    (dolist (s specs)
      (when (facep (nth 0 s))
        (set-face-attribute (nth 0 s) nil
                            :foreground (nth 1 s)
                            :height (nth 2 s)
                            :weight 'bold))))
  ;; Keep code-ish elements monospaced even with mixed-pitch, and give source
  ;; blocks a subtle raised background (Nord polar night). (zzamboni-style.)
  (when (facep 'org-block)
    (set-face-attribute 'org-block nil :inherit 'fixed-pitch :background "#333B4A"))
  (dolist (f '(org-code org-verbatim))
    (when (facep f) (set-face-attribute f nil :inherit '(shadow fixed-pitch))))
  (dolist (f '(org-table org-formula org-block-begin-line org-block-end-line
               org-document-info-keyword org-meta-line))
    (when (facep f) (set-face-attribute f nil :inherit 'fixed-pitch)))
  ;; Darker fringe so Olivetti's flanks read as page margins around the text.
  (when (facep 'fringe)
    (set-face-attribute 'fringe nil :background "#242933")))

(with-eval-after-load 'org (e6/apply-nord-org-headings))
(add-hook 'enable-theme-functions #'e6/apply-nord-org-headings)

(use-package meow
  :demand t
  :init
  (setq meow-use-clipboard t
        ;; Free c/g/h/m as leader keys. By default meow's keypad reserves them
        ;; (c=C-c, h=C-h, x=C-x, m=Meta, g=C-M-), which hijacks SPC c/g/h/m
        ;; before our menus. Keep C-x on SPC x; press real Ctrl/Meta for the
        ;; rest (they pass through in normal state).
        meow-keypad-start-keys '((?x . ?x))
        meow-keypad-meta-prefix nil
        meow-keypad-ctrl-meta-prefix nil)
  :config
  (defun meow-setup ()
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
    ;; Motion state — special/read-only buffers (Dired, Help, ...)
    (meow-motion-overwrite-define-key
     '("j" . meow-next)
     '("k" . meow-prev)
     '("<escape>" . ignore))
    ;; Normal state — the editing keymap
    (meow-normal-define-key
     '("0" . meow-expand-0) '("9" . meow-expand-9) '("8" . meow-expand-8)
     '("7" . meow-expand-7) '("6" . meow-expand-6) '("5" . meow-expand-5)
     '("4" . meow-expand-4) '("3" . meow-expand-3) '("2" . meow-expand-2)
     '("1" . meow-expand-1) '("-" . negative-argument) '(";" . meow-reverse)
     '("," . meow-inner-of-thing) '("." . meow-bounds-of-thing)
     '("[" . meow-beginning-of-thing) '("]" . meow-end-of-thing)
     '("a" . meow-append) '("A" . meow-open-below)
     '("b" . meow-back-word) '("B" . meow-back-symbol)
     '("c" . meow-change) '("d" . meow-delete) '("D" . meow-backward-delete)
     '("e" . meow-next-word) '("E" . meow-next-symbol)
     '("f" . meow-find) '("g" . meow-cancel) '("G" . meow-grab)
     '("h" . meow-left) '("H" . meow-left-expand)
     '("i" . meow-insert) '("I" . meow-open-above)
     '("j" . meow-next) '("J" . meow-next-expand)
     '("k" . meow-prev) '("K" . meow-prev-expand)
     '("l" . meow-right) '("L" . meow-right-expand)
     '("m" . meow-join) '("n" . meow-search)
     '("o" . meow-block) '("O" . meow-to-block)
     '("p" . meow-yank) '("q" . meow-quit)
     '("r" . meow-replace) '("R" . meow-swap)
     '("s" . meow-kill) '("t" . meow-till) '("u" . meow-undo)
     '("U" . meow-undo-in-selection) '("v" . meow-visit)
     '("w" . meow-next-word) '("W" . meow-next-symbol)
     '("x" . meow-line) '("y" . meow-save) '("z" . meow-pop-selection)
     '("'" . repeat) '("<escape>" . ignore)))
  (meow-setup)
  (meow-global-mode 1))

(use-package magit
  :bind ("C-x g" . magit-status)
  :commands (magit-status magit-dispatch magit-file-dispatch magit-log-current magit-blame))

(defcustom e6/ai-cli-command "pi"
  "Default external CLI for `e6/pipe-to-ai'. It receives text on stdin.
Prefilled as \"pi\" (the coding agent you use); the command is still editable at
the prompt each time, so you can add flags (e.g. a prompt/argument) as needed.
Set to \"\" to always start from an empty prompt."
  :type 'string
  :group 'e6)

(defun e6/pipe-to-ai (beg end &optional replace)
  "Pipe the region (BEG END), or the whole buffer, to a CLI agent.
Without a prefix arg, show the output in *AI Output*; with a prefix arg
REPLACE the region/buffer in place."
  (interactive
   (if (use-region-p)
       (list (region-beginning) (region-end) current-prefix-arg)
     (list (point-min) (point-max) current-prefix-arg)))
  (let ((cmd (read-shell-command "Pipe to: " e6/ai-cli-command)))
    (if replace
        (shell-command-on-region beg end cmd nil t)
      (shell-command-on-region beg end cmd "*AI Output*")
      (with-current-buffer "*AI Output*"
        (view-mode 1))
      (display-buffer "*AI Output*"))))

(defun e6/toggle-theme ()
  "Toggle between `nano-dark' and `nano-light'."
  (interactive)
  (if (custom-theme-enabled-p 'nano-dark)
      (progn (disable-theme 'nano-dark) (load-theme 'nano-light :no-confirm))
    (disable-theme 'nano-light)
    (load-theme 'nano-dark :no-confirm)))

(defun e6/switch-to-minibuffer ()
  "Select the active minibuffer window, if any."
  (interactive)
  (if (active-minibuffer-window)
      (select-window (active-minibuffer-window))
    (message "No active minibuffer")))

(keymap-global-set "C-c j" #'e6/switch-to-minibuffer)

(require 'transient)

(transient-define-prefix e6/buffers-menu ()
  "Buffers."
  [["Switch"
    ("b" "Switch buffer" consult-buffer)
    ("n" "Next"          next-buffer :transient t)
    ("p" "Previous"      previous-buffer :transient t)]
   ["Manage"
    ("k" "Kill"    kill-current-buffer)
    ("s" "Save"    basic-save-buffer)
    ("r" "Revert"  revert-buffer)
    ("R" "Rename"  rename-buffer)]
   ["List"
    ("l" "Ibuffer" ibuffer)
    ("i" "Imenu"   consult-imenu)]])

(transient-define-prefix e6/files-menu ()
  "Files."
  [["Open"
    ("f" "Find file"     find-file)
    ("r" "Recent file"   consult-recent-file)
    ("d" "Dirvish"       dired)
    ("D" "Dirvish sidebar" e6/dirvish-side)]
   ["Save"
    ("s" "Save"          save-buffer)
    ("S" "Save as"       write-file)]])

(transient-define-prefix e6/windows-menu ()
  "Windows."
  [["Split"
    ("s" "Below" split-window-below)
    ("v" "Right" split-window-right)]
   ["Move / Remove"
    ("o" "Other"   other-window)
    ("d" "Delete"  delete-window)
    ("m" "Maximize" delete-other-windows)
    ("=" "Balance" balance-windows)]])

(transient-define-prefix e6/git-menu ()
  "Git (Magit)."
  [["Magit"
    ("g" "Status"        magit-status)
    ("d" "Dispatch"      magit-dispatch)
    ("F" "File dispatch" magit-file-dispatch)]
   ["Inspect"
    ("l" "Log"   magit-log-current)
    ("b" "Blame" magit-blame)]])

(transient-define-prefix e6/toggle-menu ()
  "Toggles."
  [["Display"
    ("l" "Line numbers"   display-line-numbers-mode)
    ("w" "Soft wrap"      visual-line-mode)
    ("t" "Truncate lines" toggle-truncate-lines)
    ("f" "Fill column"    display-fill-column-indicator-mode)]
   ["Look"
    ("m" "Mixed pitch"    mixed-pitch-mode)
    ("o" "Olivetti margins" olivetti-mode)
    ("T" "Dark/light"     e6/toggle-theme)]
   ["Workflow"
    ("R" "Read-aloud/dictate" e6/readback-mode)
    ("p" "Pomodoro / timer"   e6/timer-menu)]])

(transient-define-prefix e6/help-menu ()
  "Help."
  [["Describe"
    ("f" "Function" describe-function)
    ("v" "Variable" describe-variable)
    ("k" "Key"      describe-key)
    ("m" "Mode"     describe-mode)]
   ["Search"
    ("a" "Apropos"  apropos-command)
    ("i" "Info"     info)]])

;; Direct window switch (skips the windows menu), works in any state.
(keymap-global-set "M-o" #'other-window)

(with-eval-after-load 'meow
  (meow-leader-define-key
   ;; Quick access
   '("SPC" . execute-extended-command)
   '("."   . find-file)
   '(","   . consult-buffer)
   '("/"   . consult-line)
   '("TAB" . comment-line)
   '("u"   . universal-argument)
   '("c"   . org-capture)
   '("k"   . kill-current-buffer)
   '("j"   . e6/switch-to-minibuffer)
   '("o"   . other-window)
   '("|"   . e6/pipe-to-ai)
   ;; Menus
   '("p"   . e6/project-menu)
   '("b"   . e6/buffers-menu)
   '("f"   . e6/files-menu)
   '("g"   . e6/git-menu)
   '("h"   . e6/help-menu)
   '("l"   . e6/launch-menu)
   '("m"   . himalaya)
   '("n"   . e6/notes-menu)
   '("r"   . e6/research-menu)
   '("s"   . e6/search-menu)
   '("t"   . e6/toggle-menu)
   '("w"   . e6/windows-menu)))

(use-package vertico
  :bind (:map vertico-map
         ("C-j" . vertico-next)
         ("C-k" . vertico-previous)
         ("C-f" . vertico-exit)
         :map minibuffer-local-map
         ("M-h" . backward-kill-word))
  :custom
  (vertico-cycle t)
  :init
  (vertico-mode)
  (vertico-mouse-mode))

(use-package orderless
  :custom
  (completion-styles '(orderless basic))
  (completion-category-defaults nil)
  (completion-category-overrides '((file (styles partial-completion)))))

(use-package marginalia
  :after vertico
  :init
  (marginalia-mode))

(use-package nerd-icons-completion
  :if (find-font (font-spec :name "Symbols Nerd Font Mono"))
  :after (marginalia nerd-icons)
  :hook (marginalia-mode . nerd-icons-completion-marginalia-setup)
  :init
  (nerd-icons-completion-mode))

(use-package consult
  :after vertico
  :hook (completion-list-mode . consult-preview-at-point-mode)
  :bind (("C-x b"   . consult-buffer)
         ("C-x 4 b" . consult-buffer-other-window)
         ("C-x r b" . consult-bookmark)
         ("M-y"     . consult-yank-pop)
         ("M-g g"   . consult-goto-line)
         ("M-g o"   . consult-outline)
         ("M-g i"   . consult-imenu)
         ("M-s l"   . consult-line)
         ("M-s r"   . consult-ripgrep)
         ("M-s g"   . consult-grep)
         ("M-s f"   . consult-find)
         :map minibuffer-local-map
         ("M-r"     . consult-history))
  :init
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)
  :config
  (consult-customize
   consult-ripgrep consult-grep consult-git-grep
   consult-bookmark consult-recent-file consult-xref
   :preview-key '(:debounce 0.4 any))
  (setq consult-narrow-key "<"))

(use-package embark
  :bind (("C-."   . embark-act)
         ("C-;"   . embark-dwim)
         ("C-h B" . embark-bindings))
  :init
  (setq prefix-help-command #'embark-prefix-help-command))

(use-package embark-consult
  :after (embark consult)
  :hook (embark-collect-mode . consult-preview-at-point-mode))

(use-package corfu
  :hook ((prog-mode . corfu-mode)
         (shell-mode . corfu-mode))
  :bind (:map corfu-map
         ("C-n"     . corfu-next)
         ("C-p"     . corfu-previous)
         ("<escape>" . corfu-quit)
         ("<return>" . corfu-insert))
  :custom
  (corfu-auto nil)              ; manual only — keeps prose writing clean
  (corfu-cycle t)
  (corfu-count 12)
  (corfu-preselect 'prompt)
  (tab-always-indent 'complete)
  :init
  (global-corfu-mode))

(use-package kind-icon
  :after corfu
  :custom
  (kind-icon-default-face 'corfu-default)
  (kind-icon-blend-background nil)
  :config
  (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter)
  ;; Keep icon colours in sync when the theme changes (theme-agnostic).
  (add-hook 'enable-theme-functions
            (lambda (&rest _) (when (fboundp 'kind-icon-reset-cache)
                                (kind-icon-reset-cache)))))

(use-package cape
  ;; Not C-c p: meow's leader falls back to C-c, so C-c p would hijack SPC p
  ;; (project). Cape's manual backends live under C-c e instead.
  :bind ("C-c e" . cape-prefix-map)
  :init
  (add-hook 'completion-at-point-functions #'cape-dabbrev)
  (add-hook 'completion-at-point-functions #'cape-file)
  (add-hook 'completion-at-point-functions #'cape-elisp-block))

(transient-define-prefix e6/search-menu ()
  "Search."
  [["In buffer"
    ("s" "Line"    consult-line)
    ("i" "Imenu"   consult-imenu)
    ("o" "Outline" consult-outline)]
   ["In tree"
    ("g" "Ripgrep" consult-ripgrep)
    ("G" "Grep"    consult-grep)
    ("f" "Find"    consult-find)]])

(defconst e6/notes-directory
  (expand-file-name "org"
                    (cond (e6/windows-p (or (getenv "USERPROFILE") "~"))
                          (t "~")))
  "Directory holding Org notes (outside the config repo).")

(defconst e6/config-directory
  (file-name-directory
   (or load-file-name buffer-file-name
       (expand-file-name "post-init.el" user-emacs-directory)))
  "Directory where this configuration lives (post-init.el's folder).")

(unless (file-directory-p e6/notes-directory)
  (make-directory e6/notes-directory t))

(use-package org
  :ensure nil
  :config
  (require 'org-tempo)
  (setq org-directory e6/notes-directory
        org-default-notes-file (expand-file-name "inbox.org" org-directory)
        org-agenda-files (list org-directory)
        org-startup-indented t
        org-startup-folded 'content
        org-return-follows-link t
        org-catch-invisible-edits 'show-and-error
        org-insert-heading-respect-content t
        org-ellipsis "…"
        org-tags-column 0
        org-auto-align-tags nil
        org-src-fontify-natively t
        org-src-tab-acts-natively t
        org-edit-src-content-indentation 0
        ;; ADHD "emotional sprints": tasks classed by how they FEEL, not status.
        org-todo-keywords
        '((sequence "FIRE(f!)"     ; urgent, high consequence
                    "APPROACH(a)"  ; deadline closing in
                    "BORING(b)"    ; high-friction admin
                    "PLAY(p)"      ; fun, low-friction dopamine
                    "|" "DONE(d!)"))
        ;; Dashboard stacked by energy, not a time grid (org-agenda, then "s").
        org-agenda-custom-commands
        '(("s" "Emotional Sprints Dashboard"
           ((todo "FIRE"     ((org-agenda-overriding-header "⚡ SPRINT 1 · HOT FIRE (do today)")))
            (todo "APPROACH" ((org-agenda-overriding-header "📅 SPRINT 2 · DEADLINES APPROACHING")))
            (todo "PLAY"     ((org-agenda-overriding-header "🎨 SPRINT 4 · PLAYGROUND (low-friction wins)")))
            (todo "BORING"   ((org-agenda-overriding-header "🪵 SPRINT 3 · BRAIN-DEAD ADMIN"))))))))

;; Make sure the inbox exists with the target headings.
(let ((inbox (expand-file-name "inbox.org" e6/notes-directory)))
  (unless (file-exists-p inbox)
    (with-temp-file inbox
      (insert "#+TITLE: Inbox\n#+STARTUP: overview\n\n* Inbox\n\n* Tasks\n"))))

(with-eval-after-load 'org
  ;; Low-friction: just spit it out — no drawers, tags or scheduling.
  (setq org-capture-templates
        '(("i" "Inbox — just dump it" entry
           (file+headline org-default-notes-file "Inbox")
           "* %?\n" :empty-lines 1)
          ("f" "FIRE (urgent)" entry
           (file+headline org-default-notes-file "Tasks")
           "* FIRE %?\n" :empty-lines 1)
          ("p" "PLAY (fun / low-friction)" entry
           (file+headline org-default-notes-file "Tasks")
           "* PLAY %?\n" :empty-lines 1)
          ("b" "BORING (admin)" entry
           (file+headline org-default-notes-file "Tasks")
           "* BORING %?\n" :empty-lines 1))))

(keymap-global-set "C-c c" #'org-capture)

(use-package org-pomodoro
  :commands (org-pomodoro)
  :custom
  (org-pomodoro-length 25)
  (org-pomodoro-short-break-length 5)
  (org-pomodoro-long-break-length 15)
  (org-pomodoro-manual-break t))

;; Wrappers so the menu entries are always valid commands (org-pomodoro-kill
;; isn't autoloaded on its own).
(defun e6/pomodoro-start ()
  "Start / interact with a Pomodoro on the current task."
  (interactive) (require 'org-pomodoro) (call-interactively 'org-pomodoro))
(defun e6/pomodoro-stop ()
  "Stop the running Pomodoro."
  (interactive) (require 'org-pomodoro)
  (when (fboundp 'org-pomodoro-kill) (org-pomodoro-kill)))

(transient-define-prefix e6/timer-menu ()
  "Timers."
  [["Pomodoro (25/5)"
    ("p" "Start (on task)"   e6/pomodoro-start)
    ("k" "Stop"              e6/pomodoro-stop)]
   ["Countdown timer"
    ("s" "Set countdown"     org-timer-set-timer)
    ("SPC" "Pause / resume"  org-timer-pause-or-continue)
    ("x" "Stop"              org-timer-stop)]
   ["Relative timer"
    ("r" "Start / reset"     org-timer-start)
    ("i" "Insert time"       org-timer)]])

(use-package toc-org
  :hook (org-mode . toc-org-enable))

(use-package valign
  :hook (org-mode . valign-mode)
  :custom
  (valign-fancy-bar t))

(use-package org-transclusion
  :after org
  :commands (org-transclusion-add org-transclusion-add-all org-transclusion-mode))

(use-package org-download
  :after org
  :custom
  (org-download-method 'directory)
  (org-download-image-dir (expand-file-name "images" e6/notes-directory))
  (org-download-heading-lvl nil)
  :config
  (when e6/windows-p
    ;; Use PowerShell to grab the clipboard image on Windows.
    (setq org-download-screenshot-method "powershell -Command \"(Get-Clipboard -Format Image).Save('%s')\"")))

(use-package elfeed
  :commands elfeed
  :config
  (setq elfeed-search-filter "@2-weeks-ago"
        elfeed-feeds
        '(("https://linguistlist.org/issues/rss/calls"    ll cfp)
          ("https://linguistlist.org/issues/rss/confs"    ll conferences)
          ("https://linguistlist.org/issues/rss/jobs"     ll jobs)
          ("https://linguistlist.org/issues/rss/diss"     ll dissertations)
          ("https://linguistlist.org/issues/rss/books"    ll books)
          ("https://linguistlist.org/issues/rss/software" ll tools)
          ("https://linguistlist.org/issues/rss/media"    ll media)
          ("https://linguistlist.org/issues/rss/toc"      ll journals)
          ("https://languagelog.ldc.upenn.edu/nll/?feed=rss2" blog languagelog))))

(use-package elfeed-goodies
  :after elfeed
  :config
  (elfeed-goodies/setup)
  (setq elfeed-goodies/entry-pane-size 0.5))

(defun e6/open-guide ()
  "Open the Org & notes starter guide."
  (interactive)
  (find-file (expand-file-name "guide.org" e6/config-directory)))

(defun e6/open-inbox ()
  "Open the capture inbox."
  (interactive)
  (find-file (expand-file-name "inbox.org" e6/notes-directory)))

(defun e6/sprints-dashboard ()
  "Open the Emotional Sprints agenda dashboard."
  (interactive)
  (org-agenda nil "s"))

(transient-define-prefix e6/notes-menu ()
  "Notes & research."
  [["Capture / open"
    ("c" "Capture"     org-capture)
    ("i" "Inbox"       e6/open-inbox)
    ("a" "Agenda"      org-agenda)
    ("s" "Sprints board" e6/sprints-dashboard)
    ("G" "Guide"       e6/open-guide)]
   ["Transclude"
    ("t" "Add here"    org-transclusion-add)
    ("T" "Mode"        org-transclusion-mode)]
   ["Media / read"
    ("d" "Paste image" org-download-clipboard)
    ("e" "Elfeed"      elfeed)]])

(defconst e6/bibliography
  (expand-file-name "references.bib" e6/notes-directory)
  "Path to the BibTeX file (export from Zotero).")

(use-package citar
  :commands (citar-open citar-open-entry citar-insert-citation)
  :custom
  (citar-bibliography (list e6/bibliography))
  (citar-notes-paths (list e6/notes-directory))
  (org-cite-global-bibliography (list e6/bibliography))
  (org-cite-insert-processor 'citar)
  (org-cite-follow-processor 'citar)
  (org-cite-activate-processor 'citar)
  ;; Not C-c b: that would hijack the leader's SPC b (buffers). Use C-c i
  ;; (insert citation); SPC r c also inserts a citation.
  :bind ("C-c i" . citar-insert-citation))

(use-package citar-embark
  :after (citar embark)
  :config
  (citar-embark-mode))

(use-package pdf-tools
  :defer t
  :init
  (pdf-loader-install)
  :custom
  (pdf-view-display-size 'fit-page))

(use-package djvu
  :defer t)

(use-package org-noter
  :commands (org-noter)
  :custom
  (org-noter-notes-search-path (list e6/notes-directory))
  (org-noter-always-create-frame nil)
  (org-noter-kill-frame-at-session-end nil))

(use-package jinx
  :if (and (not e6/windows-p) (executable-find "enchant-2"))
  :hook ((text-mode . jinx-mode)
         (org-mode  . jinx-mode))
  :custom
  (jinx-languages "en_US es")
  :bind ("M-$" . jinx-correct))

;; Portable fallback when jinx is unavailable.
(when (or e6/windows-p (not (executable-find "enchant-2")))
  (setq ispell-program-name (or (executable-find "hunspell")
                                (executable-find "aspell")))
  (when ispell-program-name
    (add-hook 'text-mode-hook #'flyspell-mode)))

(defun e6/spell-correct ()
  "Correct the word at point with whatever speller is active."
  (interactive)
  (cond ((bound-and-true-p jinx-mode)      (call-interactively #'jinx-correct))
        ((bound-and-true-p flyspell-mode)  (call-interactively #'flyspell-correct-word-before-point))
        (t                                  (call-interactively #'ispell-word))))

(setq default-input-method "ipa-praat")

(use-package quarto-mode
  :mode ("\\.qmd\\'" . poly-quarto-mode))

(use-package ox-typst
  :after org)

(transient-define-prefix e6/research-menu ()
  "Research."
  [["Citations"
    ("c" "Insert citation" citar-insert-citation)
    ("o" "Open resource"   citar-open)
    ("e" "Open entry"      citar-open-entry)]
   ["PDF / notes"
    ("p" "Org-noter"       org-noter)
    ("v" "Open PDF/file"   find-file)]
   ["Input / spell"
    ("i" "Toggle IPA"      toggle-input-method)
    ("s" "Correct word"    e6/spell-correct)]
   ["Linguistics"
    ("l" "Ling examples"   e6/ling-menu)]])

(when (executable-find "uv")
  (with-eval-after-load 'ob-python
    (setq org-babel-python-command "uv run python"))
  (with-eval-after-load 'python
    (setq python-shell-interpreter "uv"
          python-shell-interpreter-args "run python -i")))

(use-package markdown-mode :mode ("\\.md\\'" "\\.markdown\\'"))
(use-package yaml-mode     :mode ("\\.ya?ml\\'"))
(use-package toml-mode     :mode ("\\.toml\\'"))
(use-package lua-mode      :mode ("\\.lua\\'"))
(use-package typst-ts-mode :mode ("\\.typ\\'"))   ; needs the typst tree-sitter grammar
(add-to-list 'auto-mode-alist '("\\.rs\\'" . rust-ts-mode))  ; rust-ts is built in
;; .qmd is handled by quarto-mode (see Research pass); Python is built in.

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

(defvar e6/eglot-servers
  '((python-mode    . ("basedpyright-langserver" "pyright-langserver" "pylsp"))
    (python-ts-mode . ("basedpyright-langserver" "pyright-langserver" "pylsp"))
    (rust-ts-mode   . ("rust-analyzer"))
    (lua-mode       . ("lua-language-server"))
    (typst-ts-mode  . ("tinymist"))
    (yaml-mode      . ("yaml-language-server"))
    (toml-mode      . ("taplo"))
    (conf-toml-mode . ("taplo"))
    (markdown-mode  . ("marksman")))
  "Major mode -> candidate LSP server executables.")

(defun e6/maybe-eglot ()
  "Start eglot only when a language server for this buffer is installed."
  (when (and buffer-file-name
             (seq-some #'executable-find
                       (cdr (assq major-mode e6/eglot-servers))))
    (eglot-ensure)))

(dolist (m '(python-mode python-ts-mode rust-ts-mode lua-mode typst-ts-mode
             yaml-mode toml-mode conf-toml-mode markdown-mode))
  (add-hook (intern (format "%s-hook" m)) #'e6/maybe-eglot))

(with-eval-after-load 'eglot
  (setq eglot-autoshutdown t))

(defcustom e6/pandoc-ling-filter ""
  "Path to pandoc-ling.lua. When set, it's added to pandoc exports
so linguistic examples render. See https://github.com/cysouw/pandoc-ling."
  :type 'string :group 'e6)

(defun e6/export-current (target)
  "Export the current file to TARGET (\"docx\", \"html\", or \"pdf\").
Uses quarto for .qmd (code execution); pandoc for Org/Markdown/etc.
PDF goes through Typst (no LaTeX needed). pandoc-ling filter added if set."
  (let ((f (buffer-file-name)))
    (unless f (user-error "Buffer has no file"))
    (let* ((ext (downcase (or (file-name-extension f) "")))
           (out (concat (file-name-sans-extension f) "." target))
           (ling (if (and e6/pandoc-ling-filter
                          (not (string-empty-p e6/pandoc-ling-filter)))
                     (format " --lua-filter %s"
                             (shell-quote-argument e6/pandoc-ling-filter))
                   ""))
           ;; No standalone pandoc — use quarto's bundled one via `quarto pandoc`.
           (cmd (if (string= ext "qmd")
                    (format "quarto render %s --to %s"
                            (shell-quote-argument f) target)
                  (format "quarto pandoc %s -o %s%s%s"
                          (shell-quote-argument f)
                          (shell-quote-argument out)
                          (if (string= target "pdf") " --pdf-engine=typst" "")
                          ling))))
      (async-shell-command cmd (format "*export:%s*" target)))))

(defun e6/export-docx () (interactive) (e6/export-current "docx"))
(defun e6/export-html () (interactive) (e6/export-current "html"))
(defun e6/export-pdf  () (interactive) (e6/export-current "pdf"))

(defun e6/typst-compile ()
  "Compile the current .typ file to PDF with typst."
  (interactive)
  (let ((f (buffer-file-name)))
    (unless f (user-error "Buffer has no file"))
    (async-shell-command
     (format "typst compile %s" (shell-quote-argument f)) "*typst*")))

(defun e6/ling-example ()
  "Insert a pandoc-ling numbered example; point lands in the body."
  (interactive)
  (insert "::: ex\n")
  (let ((p (point))) (insert "\n:::\n") (goto-char p)))

(defun e6/ling-example-labeled (label)
  "Insert a labeled pandoc-ling example (referable with [@LABEL])."
  (interactive "sExample label (for [@label]): ")
  (insert (format "::: {#%s .ex}\n" label))
  (let ((p (point))) (insert "\n:::\n") (goto-char p)))

(defun e6/ling-interlinear ()
  "Insert a 4-line interlinear block (header/source/gloss/translation)."
  (interactive)
  (insert "::: ex\n| ")
  (let ((p (point))) (insert "\n| \n| \n| \n:::\n") (goto-char p)))

(defun e6/ling-ref (label)
  "Insert a pandoc-ling cross-reference [@LABEL]."
  (interactive "sReference label: ")
  (insert (format "[@%s]" label)))

(transient-define-prefix e6/ling-menu ()
  "Linguistic examples (pandoc-ling)."
  [["Insert"
    ("e" "Example"          e6/ling-example)
    ("i" "Interlinear (4)"  e6/ling-interlinear)
    ("l" "Labeled example"  e6/ling-example-labeled)
    ("r" "Cross-ref [@…]"   e6/ling-ref)]])

(use-package prodigy
  :commands (prodigy)
  :config
  ;; The URL is put in the name so it's visible in the prodigy list; press `b'
  ;; on a running service to open it.
  (prodigy-define-service
    :name "marimo  ·  http://localhost:2718"
    ;; Run the marimo binary DIRECTLY (install once: `uv tool install marimo`)
    ;; so prodigy's process IS marimo — Stop then actually stops it. A `uv run'
    ;; wrapper left marimo orphaned when the wrapper was killed.
    :command "marimo"
    :args '("edit" "--headless" "--port" "2718")
    :cwd "~/"
    :url "http://localhost:2718"
    :stop-signal 'sigint
    :kill-process-buffer-on-stop t)
  (prodigy-define-service
    :name "BentoPDF  ·  http://localhost:3000"
    :command "podman"
    ;; --replace clears a leftover container of the same name; no -d so prodigy
    ;; owns it and stopping the service stops the container.
    :args '("run" "--replace" "--rm" "--name" "bentopdf" "-p" "3000:8080"
            "ghcr.io/alam00000/bentopdf-simple:latest")
    :url "http://localhost:3000"
    :stop-signal 'sigterm
    :kill-process-buffer-on-stop t))

(defun e6/marimo-here (dir)
  "Launch `marimo edit' in DIR using that directory's own uv environment.
Runs as an Emacs child process, so it stops when Emacs quits and shows in
`list-processes' (where you can also kill it)."
  (interactive
   (list (read-directory-name
          "Marimo in directory: "
          (or (and buffer-file-name (file-name-directory buffer-file-name))
              default-directory))))
  (let ((default-directory dir))
    (start-process "marimo-here" "*marimo*" "uv" "run" "marimo" "edit")
    (message "marimo starting in %s (see *marimo*; stop via M-x list-processes)"
             dir)))

(transient-define-prefix e6/launch-menu ()
  "Launch & convert."
  [["Convert current file"
    ("w" "→ Word"            e6/export-docx)
    ("h" "→ HTML"            e6/export-html)
    ("p" "→ PDF (Typst)"     e6/export-pdf)
    ("t" "Typst compile → PDF" e6/typst-compile)]
   ["Run / services"
    ("m" "marimo here (uv env)" e6/marimo-here)
    ("s" "Services (prodigy)"   prodigy)
    ("P" "Emacs processes"      list-processes)]])

(use-package himalaya
  :commands (himalaya)
  :custom
  ;; Assumes `himalaya' is on PATH; set an absolute path here if not.
  (himalaya-executable "himalaya"))

(use-package enlight
  :demand t
  :config
  (setq enlight-content
        (concat
         (propertize "\n  E6's Emacs — scholar's desk\n\n" 'face 'shadow)
         (enlight-menu
          '(("Notes"
             ("Capture"       org-capture         "c")
             ("Inbox"         e6/open-inbox       "i")
             ("Agenda"        org-agenda          "a")
             ("Guide"         e6/open-guide       "g"))
            ("Open"
             ("Recent file"   consult-recent-file "r")
             ("Find file"     find-file           "f")
             ("Switch buffer" consult-buffer      "b"))
            ("Do"
             ("Magit"         magit-status        "m")
             ("Elfeed"        elfeed              "e")
             ("Edit config"   (find-file (expand-file-name "Config.org" e6/config-directory)) "C"))))))
  (setopt initial-buffer-choice #'enlight))

(defgroup e6-readback nil "Read-aloud + dictation workflow." :group 'e6)

(defcustom e6/readback-tts-engine 'pocket
  "Text-to-speech engine: `pocket' (Kyutai pocket-tts, better Spanish) or `piper'."
  :type '(choice (const pocket) (const piper)) :group 'e6-readback)

;; --- pocket-tts (default): run `pocket-tts serve' as a warm HTTP server ---
(defcustom e6/readback-pocket-serve-command
  (if (executable-find "uv")
      '("uvx" "pocket-tts" "serve")
    '("pocket-tts" "serve"))
  "Command (list) that starts the pocket-tts HTTP server.
Host/port/language/voice flags are appended automatically."
  :type '(repeat string) :group 'e6-readback)
(defcustom e6/readback-tts-host "127.0.0.1"
  "Host for the pocket-tts server." :type 'string :group 'e6-readback)
(defcustom e6/readback-tts-port 8000
  "Port for the pocket-tts server." :type 'integer :group 'e6-readback)
(defcustom e6/readback-pocket-language-en ""
  "pocket-tts --language value for English (empty = default English model)."
  :type 'string :group 'e6-readback)
(defcustom e6/readback-pocket-language-es "spanish_24l"
  "pocket-tts --language value for Spanish (24-layer = higher quality)."
  :type 'string :group 'e6-readback)
(defcustom e6/readback-pocket-voice-en "alba"
  "pocket-tts default voice for English." :type 'string :group 'e6-readback)
(defcustom e6/readback-pocket-voice-es "lola"
  "pocket-tts default voice for Spanish." :type 'string :group 'e6-readback)
(defcustom e6/readback-pocket-voices-en
  '("alba" "george" "mary" "eve" "michael" "jane")
  "English pocket-tts voices to cycle through with <f5>."
  :type '(repeat string) :group 'e6-readback)
(defcustom e6/readback-pocket-voices-es '("lola")
  "Spanish pocket-tts voices to cycle through with <f5>."
  :type '(repeat string) :group 'e6-readback)

;; --- piper (fallback engine): per-invocation synthesis ---
(defcustom e6/readback-piper-executable "piper"
  "Piper TTS executable." :type 'string :group 'e6-readback)
(defcustom e6/readback-piper-voice-en
  (expand-file-name "~/.local/share/piper/en_US-lessac-medium.onnx")
  "Piper English voice model (.onnx)." :type 'string :group 'e6-readback)
(defcustom e6/readback-piper-voice-es
  (expand-file-name "~/.local/share/piper/es_ES-davefx-medium.onnx")
  "Piper Spanish voice model (.onnx)." :type 'string :group 'e6-readback)
(defcustom e6/readback-mpv-executable "mpv"
  "Media player used for playback (needs IPC for pause/resume)."
  :type 'string :group 'e6-readback)
(defcustom e6/readback-mpv-socket "/tmp/e6-readback-mpv.sock"
  "Unix socket for mpv IPC." :type 'string :group 'e6-readback)
(defcustom e6/readback-server-command
  (if (executable-find "uv")
      '("uv" "run" "--with" "nemo_toolkit[asr]" "python")
    '("python3"))
  "Command (list) that launches the Parakeet server; the script path is appended.
Defaults to uv when available (uv resolves/caches nemo on first run, so it works
with no manual venv). Other options:
  (\"python3\")                                  ; a Python with nemo installed
  (\"/home/you/.venvs/parakeet/bin/python\")     ; a uv- or venv-managed Python"
  :type '(repeat string) :group 'e6-readback)
(defcustom e6/readback-stt-port 8123
  "Localhost port for the Parakeet server." :type 'integer :group 'e6-readback)
(defcustom e6/readback-record-command
  '("arecord" "-q" "-f" "S16_LE" "-r" "16000" "-c" "1")
  "Command (list) to record the mic; the output WAV path is appended."
  :type '(repeat string) :group 'e6-readback)
(defcustom e6/readback-comment-prefix "# "
  "Prefix for inserted Org comment lines." :type 'string :group 'e6-readback)

(defcustom e6/readback-speed 1.0
  "Playback speed multiplier for read-aloud." :type 'number :group 'e6-readback)

(defvar e6/readback-language 'es
  "Current TTS language (es or en). Default Spanish; toggle live with <f6>.")
(defvar e6/readback--stt-proc nil)
(defvar e6/readback--tts-proc nil "pocket-tts serve process.")
(defvar e6/readback--tts-lang nil "Language the running TTS server was started with.")
(defvar e6/readback--play-proc nil)
(defvar e6/readback--rec-proc nil)
(defvar e6/readback--recording nil)
(defvar e6/readback--rec-file nil)
(defvar e6/readback--anchor nil
  "Marker at the end of the paragraph being reviewed (comment anchor).")
(defvar e6/readback--units nil
  "Ordered list of paragraph/heading plists (:beg :end :text :wav :state) to read.")
(defvar e6/readback--pos 0 "Index into `e6/readback--units' currently playing.")
(defvar e6/readback--playing nil "Non-nil while a read-through is active.")

(defun e6/readback--at-heading-p ()
  "Non-nil if point is on a heading (Org `*' or Markdown/QMD `#')."
  (if (derived-mode-p 'org-mode)
      (org-at-heading-p)
    (looking-at-p "^#+[ \t]")))

(defun e6/readback--heading-title ()
  "Clean title of the heading at point."
  (if (derived-mode-p 'org-mode)
      (org-get-heading t t t t)
    (save-excursion
      (beginning-of-line)
      (if (looking-at "^#+[ \t]+\\(.*?\\)[ \t]*$")
          (match-string-no-properties 1) ""))))

(defun e6/readback--comment-re ()
  "Regexp for an existing dictation comment line in this buffer.
Org uses `# …'; Markdown/QMD use HTML comments `<!-- … -->' so they don't
export and don't collide with Markdown `#' headings."
  (if (derived-mode-p 'org-mode) "^[ \t]*#\\(?: \\|$\\)" "^[ \t]*<!--"))

(defun e6/readback--format-comment (line)
  "Wrap LINE as a non-exporting comment for this buffer's format."
  (if (derived-mode-p 'org-mode)
      (concat e6/readback-comment-prefix line)
    (format "<!-- %s -->" line)))

(defun e6/readback--para-bounds ()
  "Return (BEG . END) of the current paragraph's prose, excluding comments."
  (save-excursion
    (let ((cre (e6/readback--comment-re)) beg end)
      (backward-paragraph)
      (skip-chars-forward "\n")
      (setq beg (point))
      (while (and (not (eobp))
                  (not (looking-at-p "[ \t]*$"))
                  (not (looking-at-p cre)))
        (forward-line 1))
      (setq end (point))
      (cons beg end))))

(defun e6/readback--comment-insert-point ()
  "Point after the reviewed paragraph's existing comments, so notes stack."
  (save-excursion
    (goto-char (or (and (markerp e6/readback--anchor)
                        (marker-position e6/readback--anchor))
                   (cdr (e6/readback--para-bounds))))
    (let ((cre (e6/readback--comment-re)))
      (while (and (not (eobp)) (looking-at-p cre))
        (forward-line 1)))
    (point)))

(defun e6/readback--insert-comment (text)
  "Insert TEXT as comment line(s), stacked after any existing ones."
  (let ((pt (e6/readback--comment-insert-point)))
    (save-excursion
      (goto-char pt)
      (unless (bolp) (insert "\n"))
      (dolist (line (split-string (string-trim text) "\n"))
        (insert (e6/readback--format-comment line) "\n")))))

;; --- pocket-tts warm server -------------------------------------------------
(defun e6/readback--pocket-lang ()
  (if (eq e6/readback-language 'es)
      e6/readback-pocket-language-es e6/readback-pocket-language-en))
(defun e6/readback--pocket-voice ()
  (if (eq e6/readback-language 'es)
      e6/readback-pocket-voice-es e6/readback-pocket-voice-en))

(defun e6/readback--start-tts-server (&optional force)
  "Start (or restart, if FORCE or language changed) the pocket-tts server."
  (when (eq e6/readback-tts-engine 'pocket)
    (when (or force
              (not (process-live-p e6/readback--tts-proc))
              (not (eq e6/readback--tts-lang e6/readback-language)))
      (when (process-live-p e6/readback--tts-proc)
        (delete-process e6/readback--tts-proc))
      (let* ((lang (e6/readback--pocket-lang))
             (voice (e6/readback--pocket-voice))
             (args (append e6/readback-pocket-serve-command
                           (list "--host" e6/readback-tts-host
                                 "--port" (number-to-string e6/readback-tts-port))
                           (unless (string-empty-p lang)  (list "--language" lang))
                           (unless (string-empty-p voice) (list "--default-voice" voice)))))
        (setq e6/readback--tts-proc (apply #'start-process "e6-tts" "*e6-tts*" args)
              e6/readback--tts-lang e6/readback-language)
        (message "readback: starting pocket-tts (%s) in *e6-tts*…" e6/readback-language)))))

(defun e6/readback--stop-tts-server ()
  (when (process-live-p e6/readback--tts-proc)
    (delete-process e6/readback--tts-proc))
  (setq e6/readback--tts-lang nil))

;; --- synthesis (asynchronous, so we can prefetch ahead) ---------------------
(defun e6/readback--synth-command (text-file wav)
  "Shell command string that synthesizes TEXT-FILE to WAV (Linux)."
  (if (eq e6/readback-tts-engine 'piper)
      (format "%s --model %s --output_file %s < %s"
              (shell-quote-argument e6/readback-piper-executable)
              (shell-quote-argument (if (eq e6/readback-language 'es)
                                        e6/readback-piper-voice-es
                                      e6/readback-piper-voice-en))
              (shell-quote-argument wav)
              (shell-quote-argument text-file))
    ;; pocket-tts HTTP server: read the text field from the file
    (format "curl -s -X POST -F %s -o %s http://%s:%d/tts"
            (shell-quote-argument (concat "text=<" text-file))
            (shell-quote-argument wav)
            e6/readback-tts-host e6/readback-tts-port)))

(defun e6/readback--synth-async (unit callback)
  "Synthesize UNIT's text to a temp WAV asynchronously, then call CALLBACK.
Sets UNIT's :wav and :state (ready or error)."
  (when (eq e6/readback-tts-engine 'pocket)
    (e6/readback--start-tts-server))
  (let* ((wav (make-temp-file "e6-tts" nil ".wav"))
         (txt (make-temp-file "e6-tts-in" nil ".txt")))
    (with-temp-file txt (insert (plist-get unit :text)))
    (plist-put unit :state 'synthing)
    (let ((proc (start-process-shell-command
                 "e6-synth" nil (e6/readback--synth-command txt wav))))
      (set-process-sentinel
       proc
       (lambda (p _e)
         (when (memq (process-status p) '(exit signal))
           (ignore-errors (delete-file txt))
           (if (and (file-exists-p wav)
                    (> (file-attribute-size (file-attributes wav)) 0))
               (progn (plist-put unit :wav wav) (plist-put unit :state 'ready))
             (plist-put unit :state 'error))
           (when callback (funcall callback unit))))))))

;; --- playback (mpv) + speed -------------------------------------------------
(defun e6/readback--mpv-cmd (json)
  (ignore-errors
    (let ((p (make-network-process
              :name "e6-mpv-ipc" :family 'local
              :service e6/readback-mpv-socket :coding 'utf-8)))
      (process-send-string p (concat json "\n"))
      (delete-process p))))

(defun e6/readback--pause (yes)
  (e6/readback--mpv-cmd
   (format "{\"command\":[\"set_property\",\"pause\",%s]}" (if yes "true" "false"))))

(defun e6/readback--play-wav (wav)
  "Play WAV; when it ends naturally, advance to the next unit."
  (when (process-live-p e6/readback--play-proc)
    (set-process-sentinel e6/readback--play-proc #'ignore)
    (delete-process e6/readback--play-proc))
  (setq e6/readback--play-proc
        (start-process "e6-mpv" nil e6/readback-mpv-executable
                       (format "--input-ipc-server=%s" e6/readback-mpv-socket)
                       (format "--speed=%s" e6/readback-speed)
                       "--no-terminal" "--no-video" "--idle=no" wav))
  (set-process-sentinel
   e6/readback--play-proc
   (lambda (p _e)
     (when (and (eq (process-status p) 'exit)
                (= (process-exit-status p) 0)
                e6/readback--playing)
       (setq e6/readback--pos (1+ e6/readback--pos))
       (e6/readback--play-unit)))))

;; --- sectional reading pipeline ---------------------------------------------
(defun e6/readback--section-end ()
  "End of the region to read: current Org subtree; else to the next
Markdown/QMD heading; else end of buffer."
  (save-excursion
    (cond
     ((and (derived-mode-p 'org-mode) (org-before-first-heading-p))
      (or (save-excursion (when (re-search-forward (concat "^" org-outline-regexp) nil t)
                            (line-beginning-position)))
          (point-max)))
     ((derived-mode-p 'org-mode)
      (org-back-to-heading t) (org-end-of-subtree t t))
     (t
      (end-of-line)
      (or (and (re-search-forward "^#+[ \t]" nil t) (line-beginning-position))
          (point-max))))))

(defun e6/readback--build-queue (&optional start end)
  "Collect readable units from START to END.
Default START is the current paragraph; default END is the section end."
  (let ((start (or start (save-excursion (backward-paragraph)
                                         (skip-chars-forward "\n") (point))))
        (end   (or end (e6/readback--section-end)))
        (cre   (e6/readback--comment-re))
        (units '()))
    (save-excursion
      (goto-char start)
      (while (< (point) end)
        (cond
         ((looking-at-p "[ \t]*$") (forward-line 1))          ; blank
         ((e6/readback--at-heading-p)                         ; heading (Org * / MD #)
          (let ((b (point)) (title (e6/readback--heading-title)))
            (end-of-line)
            (push (list :beg b :end (copy-marker (point)) :text (or title "")
                        :wav nil :state 'pending)
                  units)
            (forward-line 1)))
         ((looking-at-p cre) (forward-line 1))                ; existing comment
         (t                                                   ; prose paragraph
          (let ((b (point)))
            (while (and (< (point) end)
                        (not (looking-at-p "[ \t]*$"))
                        (not (looking-at-p cre))
                        (not (e6/readback--at-heading-p)))
              (forward-line 1))
            (push (list :beg b :end (copy-marker (point))
                        :text (string-trim (buffer-substring-no-properties b (point)))
                        :wav nil :state 'pending)
                  units)))))
      (nreverse
       (seq-filter (lambda (u) (not (string-empty-p (string-trim (plist-get u :text)))))
                   units)))))

(defun e6/readback--prefetch (i)
  "Start synthesizing unit I in the background if it hasn't been yet."
  (let ((u (nth i e6/readback--units)))
    (when (and u (eq (plist-get u :state) 'pending))
      (e6/readback--synth-async u #'e6/readback--on-synth-ready))))

(defun e6/readback--on-synth-ready (unit)
  "Play UNIT if it is the one we're currently waiting to play."
  (when (and e6/readback--playing
             (eq unit (nth e6/readback--pos e6/readback--units)))
    (if (eq (plist-get unit :state) 'ready)
        (e6/readback--play-wav (plist-get unit :wav))
      (setq e6/readback--pos (1+ e6/readback--pos))   ; skip on error
      (e6/readback--play-unit))))

(defun e6/readback--play-unit ()
  "Play the unit at `e6/readback--pos', prefetching the next."
  (let ((unit (nth e6/readback--pos e6/readback--units)))
    (if (null unit)
        (progn (setq e6/readback--playing nil)
               (message "Read to end of section."))
      (setq e6/readback--anchor (plist-get unit :end))  ; comments anchor here
      (e6/readback--prefetch (1+ e6/readback--pos))
      (pcase (plist-get unit :state)
        ('ready   (e6/readback--play-wav (plist-get unit :wav)))
        ('error   (setq e6/readback--pos (1+ e6/readback--pos)) (e6/readback--play-unit))
        ('pending (message "Synthesizing (%d/%d)…" (1+ e6/readback--pos) (length e6/readback--units))
                  (e6/readback--synth-async unit #'e6/readback--on-synth-ready))
        (_        (message "Synthesizing (%d/%d)…" (1+ e6/readback--pos) (length e6/readback--units)))))))

(defun e6/readback-set-speed (delta)
  "Change playback speed by DELTA; also applies to the current playback."
  (setq e6/readback-speed (max 0.5 (min 3.0 (+ e6/readback-speed delta))))
  (e6/readback--mpv-cmd
   (format "{\"command\":[\"set_property\",\"speed\",%s]}" e6/readback-speed))
  (message "readback speed: %.2fx" e6/readback-speed))

(defun e6/readback-speed-up ()   (interactive) (e6/readback-set-speed 0.1))
(defun e6/readback-speed-down () (interactive) (e6/readback-set-speed -0.1))
(defun e6/readback-speed-reset ()
  (interactive)
  (setq e6/readback-speed 1.0)
  (e6/readback--mpv-cmd "{\"command\":[\"set_property\",\"speed\",1.0]}")
  (message "readback speed: 1.00x"))

;; --- reading ----------------------------------------------------------------
(defun e6/readback-play ()
  "Read from the current paragraph to the end of the section, continuously.
Paragraphs are synthesized ahead in the background. With an active region,
read just that region."
  (interactive)
  (e6/readback-stop)
  (setq e6/readback--playing t
        e6/readback--pos 0)
  (if (use-region-p)
      (setq e6/readback--units
            (list (list :beg (region-beginning)
                        :end (copy-marker (save-excursion
                                            (goto-char (region-end))
                                            (line-beginning-position 2)))
                        :text (string-trim (buffer-substring-no-properties
                                            (region-beginning) (region-end)))
                        :wav nil :state 'pending)))
    (setq e6/readback--units (e6/readback--build-queue)))
  (if (null e6/readback--units)
      (progn (setq e6/readback--playing nil) (message "Nothing to read."))
    (when (eq e6/readback-tts-engine 'pocket) (e6/readback--start-tts-server))
    (message "Reading %d block(s) (%s, %.2fx)…  <f8> comment  <f9> pause  M-<f9> stop"
             (length e6/readback--units) e6/readback-language e6/readback-speed)
    (e6/readback--play-unit)))

(defun e6/readback--render (units)
  "Synthesize all UNITS up front, unload the TTS model, then play from cache."
  (e6/readback-stop)
  (setq e6/readback--units units e6/readback--pos 0 e6/readback--playing t)
  (if (null units)
      (progn (setq e6/readback--playing nil) (message "Nothing to read."))
    (when (eq e6/readback-tts-engine 'pocket) (e6/readback--start-tts-server))
    (message "Rendering %d block(s) to audio…" (length units))
    (let ((remaining (length units)))
      (dolist (u units)
        (e6/readback--synth-async
         u (lambda (_u)
             (setq remaining (1- remaining))
             (when (<= remaining 0)
               (e6/readback--stop-tts-server)   ; unload the TTS model
               (message "Audio ready; TTS model unloaded. Playing…")
               (e6/readback--play-unit))))))))

(defun e6/readback-render-section ()
  "Render the current section to audio, unload the TTS model, then play (<f4>).
<f7> instead keeps the model hot and synthesizes on demand. Dictation/STT still
works — only the speech (TTS) model is unloaded."
  (interactive)
  (e6/readback--render (e6/readback--build-queue)))

(defun e6/readback-render-buffer ()
  "Render the ENTIRE file to audio, unload the TTS model, then play (M-<f4>)."
  (interactive)
  (e6/readback--render (e6/readback--build-queue (point-min) (point-max))))

(defun e6/readback-next-paragraph ()
  "Skip to the next paragraph in the read-through, else move point forward."
  (interactive)
  (if (and e6/readback--playing e6/readback--units)
      (progn (setq e6/readback--pos
                   (min (1- (length e6/readback--units)) (1+ e6/readback--pos)))
             (e6/readback--play-unit))
    (forward-paragraph)))

(defun e6/readback-prev-paragraph ()
  "Skip to the previous paragraph in the read-through, else move point back."
  (interactive)
  (if (and e6/readback--playing e6/readback--units)
      (progn (setq e6/readback--pos (max 0 (1- e6/readback--pos)))
             (e6/readback--play-unit))
    (backward-paragraph)))

(defun e6/readback-stop ()
  "Stop the read-through entirely (M-<f9>)."
  (interactive)
  (setq e6/readback--playing nil)
  (when (process-live-p e6/readback--play-proc)
    (set-process-sentinel e6/readback--play-proc #'ignore)
    (delete-process e6/readback--play-proc)))

(defun e6/readback-pause-toggle ()
  "Pause or resume playback, keeping the read-through position (<f9>)."
  (interactive)
  (e6/readback--mpv-cmd "{\"command\":[\"cycle\",\"pause\"]}")
  (message "readback: pause toggled"))

(defun e6/readback-toggle-language ()
  "Toggle TTS language between English and Spanish (restarts pocket-tts)."
  (interactive)
  (setq e6/readback-language (if (eq e6/readback-language 'en) 'es 'en))
  (when (and (bound-and-true-p e6/readback-mode)
             (eq e6/readback-tts-engine 'pocket))
    (e6/readback--start-tts-server t))
  (message "readback language: %s" e6/readback-language))

(defun e6/readback-cycle-voice ()
  "Cycle to the next pocket-tts voice for the current language (restarts TTS)."
  (interactive)
  (let* ((es (eq e6/readback-language 'es))
         (voices (if es e6/readback-pocket-voices-es e6/readback-pocket-voices-en))
         (cur    (if es e6/readback-pocket-voice-es  e6/readback-pocket-voice-en))
         (next   (or (cadr (member cur voices)) (car voices))))
    (if es (setq e6/readback-pocket-voice-es next)
      (setq e6/readback-pocket-voice-en next))
    (when (and (bound-and-true-p e6/readback-mode)
               (eq e6/readback-tts-engine 'pocket))
      (e6/readback--start-tts-server t))
    (message "readback voice (%s): %s" e6/readback-language next)))

(defun e6/readback--start-server ()
  (unless (process-live-p e6/readback--stt-proc)
    (let ((process-environment
           (cons (format "E6_STT_PORT=%d" e6/readback-stt-port) process-environment))
          (script (expand-file-name "scripts/parakeet_server.py" e6/config-directory)))
      (setq e6/readback--stt-proc
            (apply #'start-process "e6-stt" "*e6-stt*"
                   (append e6/readback-server-command (list script))))
      (message "readback: loading Parakeet model in *e6-stt* (first use may wait)…"))))

(defun e6/readback--transcribe (wav)
  (with-output-to-string
    (with-current-buffer standard-output
      (call-process "curl" nil t nil "-s" "-X" "POST"
                    "--data-binary" wav
                    (format "http://127.0.0.1:%d/transcribe" e6/readback-stt-port)))))

(defun e6/readback-dictate-toggle ()
  "Pause reading and record a spoken comment; call again to stop + insert."
  (interactive)
  (if e6/readback--recording
      (e6/readback--finish-dictation)
    (e6/readback--begin-dictation)))

(defun e6/readback--begin-dictation ()
  (e6/readback--pause t)
  (setq e6/readback--rec-file (make-temp-file "e6-dictate" nil ".wav")
        e6/readback--rec-proc (apply #'start-process "e6-rec" nil
                                     (append e6/readback-record-command
                                             (list e6/readback--rec-file)))
        e6/readback--recording t)
  (message "Recording comment… press the dictate key again to stop"))

(defun e6/readback--finish-dictation ()
  (setq e6/readback--recording nil)
  (when (process-live-p e6/readback--rec-proc)
    (interrupt-process e6/readback--rec-proc)  ; SIGINT so arecord finalizes WAV
    (sleep-for 0.4))
  (let ((text (string-trim (e6/readback--transcribe e6/readback--rec-file))))
    (if (string-empty-p text)
        (message "No transcript (is the model loaded? see *e6-stt*).")
      (e6/readback--insert-comment text)
      (message "Comment added: %s" text)))
  (ignore-errors (delete-file e6/readback--rec-file))
  ;; Resume reading from where it was paused.
  (e6/readback--pause nil))

(defvar e6/readback-mode-map
  (let ((m (make-sparse-keymap)))
    (define-key m (kbd "<f4>")    #'e6/readback-render-section)
    (define-key m (kbd "M-<f4>")  #'e6/readback-render-buffer)
    (define-key m (kbd "<f5>")    #'e6/readback-cycle-voice)
    (define-key m (kbd "<f6>")    #'e6/readback-toggle-language)
    (define-key m (kbd "<f7>")    #'e6/readback-play)
    (define-key m (kbd "<f8>")    #'e6/readback-dictate-toggle)
    (define-key m (kbd "<f9>")    #'e6/readback-pause-toggle)
    (define-key m (kbd "M-<f9>")  #'e6/readback-stop)
    (define-key m (kbd "<f10>")   #'e6/readback-prev-paragraph)
    (define-key m (kbd "<f12>")   #'e6/readback-next-paragraph)
    (define-key m (kbd "M-<f10>") #'e6/readback-speed-down)
    (define-key m (kbd "M-<f12>") #'e6/readback-speed-up)
    (define-key m (kbd "C-<f12>") #'e6/readback-speed-reset)
    m)
  "Keymap for `e6/readback-mode'.")

;; nano-modeline doesn't show minor-mode lighters, so we show a live status in a
;; buffer-local header-line while the mode is on (shows EN/ES).
(defvar-local e6/readback--saved-header-line :unset
  "Header-line to restore when `e6/readback-mode' turns off.")

(defun e6/readback--header ()
  "Header-line string shown while `e6/readback-mode' is on."
  (propertize (format " 🎙 Dictation — %s%s "
                      (upcase (symbol-name e6/readback-language))
                      (if (bound-and-true-p e6/readback--recording) "  ● REC" ""))
              'face 'mode-line-emphasis))

(define-minor-mode e6/readback-mode
  "Read paragraphs aloud (pocket-tts/Piper) and dictate Org-comment notes (Parakeet).
Enabling starts the model servers; disabling kills them to free memory."
  :lighter " 🎙"
  :keymap e6/readback-mode-map
  (if e6/readback-mode
      (if (not e6/linux-p)
          (progn (setq e6/readback-mode nil)
                 (user-error "e6/readback-mode is Linux-only"))
        (e6/readback--start-server)       ; STT (Parakeet)
        (e6/readback--start-tts-server)   ; TTS (pocket-tts), if that engine
        (setq e6/readback--saved-header-line header-line-format
              header-line-format '(:eval (e6/readback--header))))
    ;; teardown: restore header-line; kill both servers, playback, recording.
    (unless (eq e6/readback--saved-header-line :unset)
      (setq header-line-format e6/readback--saved-header-line
            e6/readback--saved-header-line :unset))
    (e6/readback-stop)
    (when (process-live-p e6/readback--rec-proc) (interrupt-process e6/readback--rec-proc))
    (when (process-live-p e6/readback--stt-proc) (delete-process e6/readback--stt-proc))
    (e6/readback--stop-tts-server)
    (setq e6/readback--recording nil)))

(defun e6/readback-restart-server ()
  "Restart the Parakeet server."
  (interactive)
  (when (process-live-p e6/readback--stt-proc) (delete-process e6/readback--stt-proc))
  (e6/readback--start-server))

(provide 'post-init)
;;; post-init.el ends here
