;;; pre-init.el --- Before init -*- lexical-binding: t; -*-

;; Loaded after early-init.el, before minimal-emacs.d's init.el body / packages.
;; Generated by tangling Config.org -- do not hand-edit; edit Config.org instead.
;; (Stub: replaced on first tangle of the rebuilt Config.org.)

;;; Code:

(provide 'pre-init)
;;; pre-init.el ends here
