;;; pre-early-init.el --- Before early-init -*- lexical-binding: t; -*-

;; Loaded FIRST, before minimal-emacs.d's early-init.el body runs.
;; Generated by tangling Config.org -- do not hand-edit; edit Config.org instead.
;; (Stub: replaced on first tangle of the rebuilt Config.org.)

;;; Code:

(provide 'pre-early-init)
;;; pre-early-init.el ends here
